version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

release:
  github:
    owner: philipparndt
    name: tgh

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

brews:
  - name: tgh

    goarm: 6
    goamd64: v1

    url_template: "https://github.com/philipparndt/tgh/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: Philipp Arndt
      email: opensource@rnd7.de

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    directory: Formula

    homepage: "https://github.com/philipparndt/tgh"

    description: "Terminal UI for browsing GitHub Actions workflow runs and job logs"

    license: "MIT"

    install: |
      bin.install "tgh"

    repository:
      owner: philipparndt
      name: homebrew-tgh
      branch: main

      pull_request:
        enabled: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
